//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictrGllr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PictrGllr.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;An error occurred getting the access token: &quot;.
        /// </summary>
        public static string AccessTokenError {
            get {
                return ResourceManager.GetString("AccessTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PictrGllr.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate below.
        /// </summary>
        public static string AuthenticationText {
            get {
                return ResourceManager.GetString("AuthenticationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string AuthenticationTitle {
            get {
                return ResourceManager.GetString("AuthenticationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera initialized..
        /// </summary>
        public static string CameraReady {
            get {
                return ResourceManager.GetString("CameraReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string CameraText {
            get {
                return ResourceManager.GetString("CameraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download picture?.
        /// </summary>
        public static string DownloadQuestion {
            get {
                return ResourceManager.GetString("DownloadQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadTitle {
            get {
                return ResourceManager.GetString("DownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred talking to Flickr:.
        /// </summary>
        public static string FlickrError {
            get {
                return ResourceManager.GetString("FlickrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FrontPageTitle {
            get {
                return ResourceManager.GetString("FrontPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Pictures.
        /// </summary>
        public static string GalleryText {
            get {
                return ResourceManager.GetString("GalleryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Pictures.
        /// </summary>
        public static string MyPictureTitle {
            get {
                return ResourceManager.GetString("MyPictureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewText {
            get {
                return ResourceManager.GetString("NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Camera is not available on this phone..
        /// </summary>
        public static string NoCameraText {
            get {
                return ResourceManager.GetString("NoCameraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred getting the request token:.
        /// </summary>
        public static string RequestTokenError {
            get {
                return ResourceManager.GetString("RequestTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo has been saved to the local folder..
        /// </summary>
        public static string SavedToLocal {
            get {
                return ResourceManager.GetString("SavedToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo has been saved to camera roll..
        /// </summary>
        public static string SavedToRoll {
            get {
                return ResourceManager.GetString("SavedToRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured image available, saving photo..
        /// </summary>
        public static string SavingText {
            get {
                return ResourceManager.GetString("SavingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with tags.
        /// </summary>
        public static string SearchPictureTags {
            get {
                return ResourceManager.GetString("SearchPictureTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string ShutterText {
            get {
                return ResourceManager.GetString("ShutterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload picture?.
        /// </summary>
        public static string UploadQuestion {
            get {
                return ResourceManager.GetString("UploadQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadText {
            get {
                return ResourceManager.GetString("UploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadTitle {
            get {
                return ResourceManager.GetString("UploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Verifier code in uri:.
        /// </summary>
        public static string VerifierError {
            get {
                return ResourceManager.GetString("VerifierError", resourceCulture);
            }
        }
    }
}
